### ISSUE TITLE
Question: Is it possible to display the percentage of the download progress?

### ISSUE THREAD

**Issue by ma-zsola** [cvzi/mpv-youtube-download#11]
I usually download videos longer than 2 hours. It would be very helpful to be able to follow the download progress on the OSD continuously or with a keybind.

**Comment by cvzi** [comment]
I don't see a way to do this. 
As far as I understand the script gets the output of the executed command only when the command has finished. So I don't think the script can get the progress output of yt-dlp while it is downloading

**Comment by ma-zsola** [comment]
Thank you for the feedback.
I haven't find a solution to display yt-dlp's `--progress` command in mpv yet. Probably this is the key.

**Comment by ma-zsola** [comment]
Is it feasable to open a command prompt with the yt-dlp command, when the download started?
This way we could easly follow the process.
The setting could be optional.

I tried `os.execute()` but unfortunately I don't know the requied parameters.

**Comment by cvzi** [comment]
It's probably possible to do that. I can take a look and try it when I have some time.

Are you using Windows or another OS?

**Comment by ma-zsola** [comment]
Thank you. I am using Windows 11.

**Comment by cvzi** [comment]
I have added an option to open a new terminal for the download. I am not sure if this works on Windows 11, because I only have Windows 10 to test though.

The changes are currently on the git branch [new_terminal](https://github.com/cvzi/mpv-youtube-download/tree/new_terminal) for testing.
The main file is here: https://github.com/cvzi/mpv-youtube-download/blob/new_terminal/youtube-download.lua

Basically instead of instead of `yt-dlp ....` it will run `wt new-tab cmd /K yt-dlp ....` which should open a new Windows Terminal window or tab.
You need the new Windows Terminal: https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701 I don't know if this is pre-installed on Windows 11 or not. You can check by typing wt and Enter in a terminal, then a new window should open if it is installed.

I set it to leave the terminal open after the download, that way you can see errors. But you can change that easily, `/K`means keep the window open `/C` means close the window after the command. See line 760:
https://github.com/cvzi/mpv-youtube-download/blob/2a33861032fbeee05611b42716915a87d98ae8de/youtube-download.lua#L755-L760

**Comment by ma-zsola** [comment]
Thank you very much.

I have noticed two things:

1. If I set a custom `video_format`, the Windows Terminal says "System cannot find the path specified". No other info shown on Windows Terminal.

    My setting:
    `video_format = "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a],best[ext=mp4]",`
    It works well with the previous version and also works when I leave its default value.

2. When the terminal shows that the download is completed, and I try another download for the same video or for another video on the playlist, the OSD says that the download is in progress. But I cannot cancel the previous download.

**Comment by cvzi** [comment]
The seconds thing should be fixed with the change.

**Comment by cvzi** [comment]
The first thing is apparently the `<` symbol, which causes a problem. 
A quick Google search says you can escape it with a `^` so `^<`
```lua 
video_format = "bestvideo[height^<=1080][ext=mp4]+bestaudio[ext=m4a],best[ext=mp4]",
```
That executes the command. I am not sure, if that means that yt-dlp also correctly receives the format or not. Maybe you can test if the format works as you expect it.

Something similar may happen with other symbols, maybe `>` or `|` or even spaces, I'll have to test that. 
When I know more, I can change the script so that it automatically adds the '^' if necessary.

**Comment by ma-zsola** [comment]
> The seconds thing should be fixed with the change.

Thanks, this works great.

> The first thing is apparently the `<` symbol, which causes a problem. A quick Google search says you can escape it with a `^` so `^<`

Thanks for the tip, I can confirm that with the escaping character `^` there is no issue with symbols `<` and `>`.  The download is working and the quality is as expected.

Thank you for your help.

**Comment by cvzi** [comment]
I did some minor improvements. E.g. it now escapes with the `^` automatically.
Also I added a new option to switch the `/K` `/C` behavior.
Both options are now by default disabled
https://github.com/cvzi/mpv-youtube-download/blob/79453ae2633fe42d3edb2ac4e9d192dc03ed601a/youtube-download.lua#L103-L104

Could you please check if it still works as expected?

**Comment by ma-zsola** [comment]
I tested the new optional settings with both values. Everything works like a charm :-)
There's no need to use the escape character now. Works fine with and without the "terminal" mode.
Now, the terminal opens only in one instance, I can follow multiple parallel processes in the tabs. That's cool.
You are the best. Thank you.
